In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Vocabulary size
voc_size=10000

## One hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1624, 7016, 6143, 1304], [1624, 7016, 6143, 5912], [1624, 293, 6143, 6551], [3652, 7468, 1766, 6198, 5322], [3652, 7468, 1766, 6198, 5347], [511, 1624, 6356, 6143, 1959], [7323, 8488, 9311, 6198]]


## Word Embedding Representation 

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1624 7016 6143 1304]
 [   0    0    0    0 1624 7016 6143 5912]
 [   0    0    0    0 1624  293 6143 6551]
 [   0    0    0 3652 7468 1766 6198 5322]
 [   0    0    0 3652 7468 1766 6198 5347]
 [   0    0    0  511 1624 6356 6143 1959]
 [   0    0    0    0 7323 8488 9311 6198]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 189ms/step
[[[-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841
    0.04076329 -0.01976126  0.0089043   0.02224709 -0.0452926 ]
  [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841
    0.04076329 -0.01976126  0.0089043   0.02224709 -0.0452926 ]
  [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841
    0.04076329 -0.01976126  0.0089043   0.02224709 -0.0452926 ]
  [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841
    0.04076329 -0.01976126  0.0089043   0.02224709 -0.0452926 ]
  [-0.00504836 -0.04852678  0.02021474  0.00066561  0.04707545
   -0.03101894 -0.01429318 -0.02802101  0.01763184  0.02499868]
  [ 0.02012551  0.01212998  0.04307253 -0.01322673  0.02186741
    0.0142423   0.00312222  0.00017939  0.04704291  0.0378613 ]
  [ 0.04840192 -0.0003324   0.01666454  0.01255583  0.0427112
   -0.04235183 -0.04752209 -0.02617483  0.04900572 -0.02057655]
  [ 0.04131582 -0.01074266  0.0228146  -0.00887696 -0.00270

In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 41ms/step
[[-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841  0.04076329
  -0.01976126  0.0089043   0.02224709 -0.0452926 ]
 [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841  0.04076329
  -0.01976126  0.0089043   0.02224709 -0.0452926 ]
 [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841  0.04076329
  -0.01976126  0.0089043   0.02224709 -0.0452926 ]
 [-0.0347658   0.0320231  -0.0489274   0.00320263  0.03645841  0.04076329
  -0.01976126  0.0089043   0.02224709 -0.0452926 ]
 [-0.00504836 -0.04852678  0.02021474  0.00066561  0.04707545 -0.03101894
  -0.01429318 -0.02802101  0.01763184  0.02499868]
 [ 0.02012551  0.01212998  0.04307253 -0.01322673  0.02186741  0.0142423
   0.00312222  0.00017939  0.04704291  0.0378613 ]
 [ 0.04840192 -0.0003324   0.01666454  0.01255583  0.0427112  -0.04235183
  -0.04752209 -0.02617483  0.04900572 -0.02057655]
 [ 0.04131582 -0.01074266  0.0228146  -0.00887696 -0.00270991 -0.0162667
 

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1624, 7016, 6143, 1304])